services:
  - name: fastapi-app
    type: web
    runtime: python
    buildCommand: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    startCommand: "venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PORT
        value: 8000
